	DefTXT	OPSTR_OP1,	"SOUNDTRACK"
	DefTXT	OPSTR_OP2,	"SPINDASH"
	DefTXT	OPSTR_OP3,	"SOUND EFFECTS"

	DefTXT	OP1_1,	"JP/PAL"
	DefTXT	OP1_2,	"US"
	DefTXT	OP1_3,	"OFF"

	DefTXT	OP2_1,	"CD STYLE"
	DefTXT	OP2_2,	"MD STYLE"
	
	DefTXT	OP3_1,	"SONIC CD"
	DefTXT	OP3_2,	"CD-SONIC"
	DefTXT	OP3_3,	"MEGA DRIVE"
	DefTXT	OP3_4,	"OFF"